### ISSUE TITLE
data is right ?

### ISSUE THREAD

**Issue by syu-tan** [Cinnamon/electra_japanese#2]
I tried to see if the code you created works.
but, could not untar jawiki link here
`jawiki-20200601-pages-articles-multistream.xml.bz2`

i did it
`$ tar -jxvf ./jawiki-20200601-pages-articles-multistream.xml.bz2`

error ocuer
```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains ‘.afpbb.com/a’ where numeric off_t value expected
tar: Archive contains ‘9年7月10\346\227’ where numeric off_t value expected
tar: Archive contains ‘ー級\n|IMO\347’ where numeric off_t value expected
tar: Exiting with failure status due to previous errors
```

my env is colab notebook.

 data is right? or broken?
really same procedure ?

**Comment by syu-tan** [comment]
Waiting for an answer. Thank you.

**Comment by thaiduongx26** [comment]
@syu-tan sorry for late response. You need to extract by using wikiextractor. Pls extract dataset following: <br> `python extract_wiki_data.py`

**Comment by syu-tan** [comment]
Sorry, late.
I see. Thank you, for your time.
