### ISSUE TITLE
about demo

### ISSUE THREAD

**Issue by syu-tan** [Cinnamon/electra_japanese#3]
Thank you many times.
I want to get feature embedding from sample text on your pretrain model.
Is there a simple demo that works with the trained model?

**Comment by syu-tan** [comment]
I want to use your wonderful results
waiting for your reply

**Comment by thaiduongx26** [comment]
Hi @syu-tan , currently I do not have code for feature embedding, but you can follow 2 ways:

**Comment by thaiduongx26** [comment]
Hi @syu-tan , currently I do not have code for feature embedding, but you can follow 2 ways:
1. use `extract_features.py` from https://github.com/google-research/bert/blob/master/extract_features.py

**Comment by thaiduongx26** [comment]
Hi @syu-tan , currently I don't have code for feature embedding, but you can follow 2 ways:
1. use extract_features.py from https://github.com/google-research/bert/blob/master/extract_features.py
2. you can convert the model to PyTorch model ([link](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_electra_original_tf_checkpoint_to_pytorch.py)) and extract feature by using huggingface.

**Comment by syu-tan** [comment]
Thank you for your polite answer.
I see, i try it.

**Comment by syu-tan** [comment]
need `config.json` is mdoel structure file like BERT .
Would you please upload electra config file ?

**Comment by thaiduongx26** [comment]
@syu-tan  I have uploaded the pytorch model and `config.json` file to [Google drive](https://drive.google.com/drive/folders/1ZZ-t2LRvjlxDm-qq-7VCOp84ZkITOl3R?usp=sharing)

**Comment by syu-tan** [comment]
Thank you reply.

i can restore model rihghts.
but, tokenizer is failed.
I used huggingface according to you, then

if
`
tokenizer = ElectraTokenizer.from_pretrained("model_sentence_piece/wiki-ja.model")
`
error occurs
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 116: illegal multibyte sequence
```
shift-jis is the same error

if
`
tokenizer = ElectraTokenizer.from_pretrained("model_sentence_piece/wiki-ja.vocab")
tokens = tokenizer.encode("こんにちわ", add_special_tokens=True)
print(tokens) -> [32002, None, 32000]
`

None appears and out of vocab number.


which is right vocab file ? and What should i do ? please teach me ~

env : OSX
python 3.6.8
transformers : 3.3.1

**Comment by thaiduongx26** [comment]
@syu-tan Please use our class FullTokenizer from `model/tokenization.py`: <br> `tokenizer = FullTokenizer(vocab_file=JA_VOCAB_PATH, model_file=SENTENCEPIECE_PATH)` <br> If you wanna use huggingface class, I think you can use `XLNetTokenizer`, I'm not sure about BPE class like `SentencePieceBPETokenizer`, `ByteLevelBPETokenizer` but you can read the docs and try

**Comment by syu-tan** [comment]
thank you for your time.It worked safely.
I did a simple accuracy test with cosine similality.
[CLS] tokens is bad but, Others were amazing!
Thank you for your success

**Comment by thaiduongx26** [comment]
@syu-tan thank you
